// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using car1.Models;

#nullable disable

namespace car1.Migrations
{
    [DbContext(typeof(CarinfomanagementContext))]
    [Migration("20250207091436_addLogin")]
    partial class addLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("car1.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirBagDetails")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Bhp")
                        .HasColumnType("int")
                        .HasColumnName("BHP");

                    b.Property<int?>("BootSpace")
                        .HasColumnType("int");

                    b.Property<int?>("CarTransmissionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Engine")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Mileage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Seat")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Car__3214EC07524D0C4F");

                    b.HasIndex("CarTransmissionTypeId");

                    b.HasIndex("CarTypeId");

                    b.HasIndex(new[] { "Model" }, "UQ__Car__FB104C13DA7D6894")
                        .IsUnique()
                        .HasFilter("[Model] IS NOT NULL");

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("car1.Models.CarTransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__CarTrans__3214EC07977A8369");

                    b.ToTable("CarTransmissionType", (string)null);
                });

            modelBuilder.Entity("car1.Models.CarType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__CarType__3214EC0790C6B5C8");

                    b.ToTable("CarType", (string)null);
                });

            modelBuilder.Entity("car1.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RegisteredOffice")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Manufact__3214EC076F79689A");

                    b.ToTable("Manufacturer", (string)null);
                });

            modelBuilder.Entity("car1.Models.Car", b =>
                {
                    b.HasOne("car1.Models.CarTransmissionType", "CarTransmissionType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTransmissionTypeId")
                        .HasConstraintName("FK__Car__CarTransmis__36B12243");

                    b.HasOne("car1.Models.CarType", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeId")
                        .HasConstraintName("FK__Car__CarTypeId__35BCFE0A");

                    b.Navigation("CarTransmissionType");

                    b.Navigation("CarType");
                });

            modelBuilder.Entity("car1.Models.CarTransmissionType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("car1.Models.CarType", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
